//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "Employee Username")]
        [Required(ErrorMessage = "*")]
        public string employeeUsername { get; set; }
        [Display(Name = "Employee Name")]
        [Required(ErrorMessage = "*")]
        public string employeeName { get; set; }
        [Display(Name = "Employee Surname")]
        [Required(ErrorMessage = "*")]
        public string employeeSurname { get; set; }
        [Display(Name = "Employee Password")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Password)]
        public string employeePassword { get; set; }
        
    }
}
