//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Farmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmer()
        {
            this.farmersProducts = new HashSet<farmersProduct>();
        }

        [Display(Name = "Farmer Username")]
        [Required(ErrorMessage = "*")]
        public string FarmerUsername { get; set; }
        [Display(Name = "Farmer Name")]
        [Required(ErrorMessage = "*")]
        public string FarmerName { get; set; }
        [Display(Name = "Farmer Surname")]
        [Required(ErrorMessage = "*")]
        public string FarmerSurname { get; set; }
        [Display(Name = "Farmer Password")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Password)]
        public string FarmerPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmersProduct> farmersProducts { get; set; }
    }
}
