//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class farmersProduct
    {
        [Display(Name = "Farmer's Product")]
        [Required(ErrorMessage = "*")]
        public int farmersProduct1 { get; set; }
        [Display(Name = "Farmer Username")]
        [Required(ErrorMessage = "*")]
        public string farmersUsername { get; set; }
        [Display(Name = "Product ID")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> productID { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual Product Product { get; set; }
    }
}
