//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AuthAppDBEntities : DbContext
    {
        public AuthAppDBEntities()
            : base("name=AuthAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<farmersProduct> farmersProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        
    
        public virtual ObjectResult<st_getAllEmployees_Result> st_getAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_getAllEmployees_Result>("st_getAllEmployees");
        }
    
        public virtual ObjectResult<st_getAllFarmers_Result> st_getAllFarmers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_getAllFarmers_Result>("st_getAllFarmers");
        }
    }
}
