//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.farmersProducts = new HashSet<farmersProduct>();
        }

        [Display(Name = "Product ID")]
        [Required(ErrorMessage = "*")]
        public int productID { get; set; }
        [Display(Name = "Category ID")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> categoryID { get; set; }
        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "*")]
        public string productName { get; set; }
        [Display(Name = "Product Quantity")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> productQty { get; set; }
        [Display(Name = "Product Price")]
        [Required(ErrorMessage = "*")]
        public Nullable<decimal> productPrice { get; set; }
        [Display(Name = "Date Added")]
        [Required(ErrorMessage = "*")]
        public Nullable<System.DateTime> addDate { get; set; }

    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmersProduct> farmersProducts { get; set; }
    }
}
